# Use docker-based build environment (instead of openvz)
sudo: false
language: scala
scala:
- 2.11.6
jdk:
- oraclejdk7

cache:
  directories:
    - '$HOME/.ivy2/cache'

#branches:
#  only:
#  - master
notifications:
  email:
    recipients:
    - platform-engineering@digital.hmrc.gov.uk
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/a79927962ed4476d5d9e'
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
#after_success:
#- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'